In [ ]:
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer

c:\Users\Ali Akbar\anaconda3\envs\ml\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Ali Akbar\anaconda3\envs\ml\lib\site-packages\torch\cuda\__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [4]:
pd.set_option('display.max_colwidth', 100)
df = pd.read_csv('sample_text.csv')
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [6]:
encoder = SentenceTransformer('all-mpnet-base-v2')
vectors = encoder.encode(df.text.tolist())
vectors.shape

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1674.71it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

(8, 768)

In [8]:
index = faiss.IndexFlatL2(vectors.shape[1])
index.add(vectors)
index

In [34]:
search_query = "An apple a day, keeps the doctor away."
svec = encoder.encode([search_query])
print(svec.shape)
index.search(svec, k=1) # k = how many similar vectors to return

(1, 768)

(array([[1.2094808]], dtype=float32), array([[1]]))

In [36]:
distance ,index_items = index.search(svec, k=2)
# print(index_items)
df.loc[index_items[0]]

                                                               text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health